# Generated by Django 4.1.3 on 2023-08-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_atonormativ_assinante2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composicao',
            name='tipo_ato',
        ),
        migrations.AlterField(
            model_name='atonormativ',
            name='autoridade1',
            field=models.CharField(default='setor', max_length=45, null=True, verbose_name='Autoridade 1'),
        ),
    ]
