# Generated by Django 4.1.3 on 2023-08-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_composicao_tipo_ato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atonormativ',
            name='autoridade1',
            field=models.CharField(default='setor', max_length=45, verbose_name='Autoridade 1'),
        ),
    ]
