# Generated by Django 4.2.4 on 2023-08-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_oracleuser_padaces_sistema_usuario_usuariopadaces_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atonormativ',
            name='dt_cadastro',
            field=models.DateTimeField(null=True, verbose_name='Data de cadastro'),
        ),
    ]
