# Generated by Django 4.2.4 on 2023-08-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_atonormativ_dt_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletimgerado',
            name='status',
            field=models.CharField(choices=[('revisao', 'Revisão'), ('aprovado', 'Aprovado')], default='revisao', max_length=10),
        ),
    ]
