# Generated by Django 4.2.4 on 2023-08-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_boletimgerado_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='atonormativ',
            name='get_setor',
            field=models.CharField(default='setor nao definido', max_length=45, verbose_name='get_setor'),
        ),
    ]
