# Generated by Django 4.2.4 on 2023-08-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_atonormativ_get_setor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='atonormativ',
            table='AtoNormativ',
        ),
    ]
