# Generated by Django 4.2.4 on 2023-08-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_remove_atonormativ_get_setor_alter_atonormativ_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atonormativ',
            name='doe_numero',
        ),
        migrations.RemoveField(
            model_name='atonormativ',
            name='doe_numero_boletim',
        ),
        migrations.RemoveField(
            model_name='atonormativ',
            name='doe_pagina',
        ),
        migrations.RemoveField(
            model_name='atonormativ',
            name='doe_secao',
        ),
        migrations.AddField(
            model_name='atonormativ',
            name='setor_do_usuario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Setor do Usuário'),
        ),
    ]
