# Generated by Django 4.2.4 on 2023-08-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_remove_atonormativ_doe_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atonormativ',
            name='doe_data',
        ),
    ]
