# Generated by Django 4.2.4 on 2023-08-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_atonormativ_doe_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletimgerado',
            name='status',
        ),
    ]
