# Generated by Django 4.2.4 on 2023-08-08 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_remove_boletimgerado_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atonormativ',
            name='setor_do_usuario',
        ),
        migrations.AddField(
            model_name='atonormativ',
            name='doe_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Diário Oficial'),
        ),
        migrations.AddField(
            model_name='atonormativ',
            name='doe_numero',
            field=models.PositiveIntegerField(null=True, verbose_name='Número do Diário Oficial'),
        ),
        migrations.AddField(
            model_name='atonormativ',
            name='doe_numero_boletim',
            field=models.PositiveIntegerField(null=True, verbose_name='Número do Diário Oficial'),
        ),
        migrations.AddField(
            model_name='atonormativ',
            name='doe_pagina',
            field=models.CharField(default=1, max_length=40, verbose_name='Página do Diário Oficial'),
        ),
        migrations.AddField(
            model_name='atonormativ',
            name='doe_secao',
            field=models.CharField(default=1, max_length=40, verbose_name='Seção do Diário Oficial'),
        ),
        migrations.AddField(
            model_name='boletimgerado',
            name='status',
            field=models.CharField(choices=[('revisao', 'Revisão'), ('aprovado', 'Aprovado')], default='revisao', max_length=10),
        ),
    ]
