# Generated by Django 4.2.4 on 2023-08-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_remove_atonormativ_setor_do_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atonormativ',
            name='doe_data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do Diário Oficial'),
        ),
        migrations.AlterField(
            model_name='atonormativ',
            name='doe_pagina',
            field=models.CharField(max_length=40, verbose_name='Página do Diário Oficial'),
        ),
        migrations.AlterField(
            model_name='atonormativ',
            name='doe_secao',
            field=models.CharField(max_length=40, verbose_name='Seção do Diário Oficial'),
        ),
    ]
