# Generated by Django 4.2.4 on 2023-08-08 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_setor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setor',
        ),
    ]
