# Generated by Django 4.2.4 on 2023-08-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_atonormativ_setor_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atonormativ',
            name='setor_usuario',
            field=models.IntegerField(default='0', verbose_name='Criador'),
        ),
    ]
