# Generated by Django 4.2.4 on 2023-08-08 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_atonormativ_doe_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Composicao',
        ),
    ]
