# Generated by Django 4.2.4 on 2023-08-08 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_delete_composicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atonormativ',
            name='doe_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Diário Oficial'),
        ),
        migrations.AlterField(
            model_name='atonormativ',
            name='doe_pagina',
            field=models.CharField(default=1, max_length=40, verbose_name='Página do Diário Oficial'),
        ),
        migrations.AlterField(
            model_name='atonormativ',
            name='doe_secao',
            field=models.CharField(default=1, max_length=40, verbose_name='Seção do Diário Oficial'),
        ),
    ]
