# Generated by Django 4.2.4 on 2023-08-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_composicao_alter_atonormativ_doe_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atonormativ',
            name='setor_usuario',
            field=models.CharField(default=2, max_length=50),
        ),
    ]
