# Generated by Django 4.2.4 on 2023-08-09 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_remove_atonormativ_setor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='atonormativ',
            name='setor_uea',
            field=models.CharField(max_length=10, null=True, verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='atonormativ',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuario', verbose_name='Usuário'),
        ),
    ]
