# Generated by Django 4.2.4 on 2023-08-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_atonormativ_setor_uea_atonormativ_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atonormativ',
            name='setor_uea',
        ),
        migrations.RemoveField(
            model_name='atonormativ',
            name='usuario',
        ),
    ]
