# Generated by Django 4.2.4 on 2023-08-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_remove_atonormativ_setor_uea_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atonormativ',
            name='usr_cadastro',
        ),
        migrations.AlterField(
            model_name='atonormativ',
            name='ano',
            field=models.PositiveIntegerField(null=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='atonormativ',
            name='doe_pagina',
            field=models.CharField(max_length=40, null=True, verbose_name='Página do Diário Oficial'),
        ),
        migrations.AlterField(
            model_name='atonormativ',
            name='doe_secao',
            field=models.CharField(max_length=40, null=True, verbose_name='Seção do Diário Oficial'),
        ),
        migrations.AlterField(
            model_name='atonormativ',
            name='numero',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='atonormativ',
            name='publicado',
            field=models.CharField(default='n', max_length=1, null=True, verbose_name='Publicado'),
        ),
    ]
