# Generated by Django 4.2.4 on 2023-08-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_remove_atonormativ_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atonormativ',
            name='doe_secao',
            field=models.CharField(default='Seção', max_length=40, verbose_name='Seção do Diário Oficial'),
        ),
    ]
