# Generated by Django 4.2.4 on 2023-08-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_alter_atonormativ_doe_secao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atonormativ',
            name='autoridade2',
            field=models.CharField(default='setor', max_length=45, verbose_name='Autoridade 2'),
        ),
    ]
