# Generated by Django 4.2.4 on 2023-08-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_alter_atonormativ_autoridade2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atonormativ',
            name='doe_secao',
            field=models.CharField(max_length=40, verbose_name='Seção do Diário Oficial'),
        ),
    ]
