# Generated by Django 4.2.4 on 2023-08-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_alter_atonormativ_doe_secao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atonormativ',
            name='doe_numero',
        ),
        migrations.RemoveField(
            model_name='atonormativ',
            name='doe_pagina',
        ),
        migrations.RemoveField(
            model_name='atonormativ',
            name='doe_secao',
        ),
    ]
