# Generated by Django 4.1.3 on 2023-08-15 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_remove_atonormativ_doe_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atonormativ',
            name='criador',
        ),
    ]
