# Generated by Django 4.1.3 on 2023-08-16 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_remove_atonormativ_criador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atonormativ',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='boletimgerado',
            name='status',
        ),
        migrations.AddField(
            model_name='atonormativ',
            name='criador',
            field=models.CharField(default='user', max_length=45, verbose_name='Criador'),
        ),
        migrations.AddField(
            model_name='atonormativ',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2000, 10, 10, 4, 0, tzinfo=datetime.timezone.utc), verbose_name='Data de criação'),
        ),
        migrations.AddField(
            model_name='atonormativ',
            name='doe_numero',
            field=models.PositiveIntegerField(null=True, verbose_name='Número do Diário Oficial'),
        ),
        migrations.AddField(
            model_name='atonormativ',
            name='usr_cadastro',
            field=models.CharField(default='enzo', max_length=40, verbose_name='Usuário de cadastro'),
        ),
        migrations.AlterField(
            model_name='atonormativ',
            name='dt_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2000, 10, 10, 4, 0, tzinfo=datetime.timezone.utc), verbose_name='Data de cadastro'),
        ),
        migrations.AlterField(
            model_name='atonormativ',
            name='publicado',
            field=models.CharField(default='n', max_length=1, verbose_name='Publicado'),
        ),
    ]
