# Generated by Django 4.1.3 on 2023-08-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_remove_atonormativ_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atonormativ',
            name='criador',
        ),
        migrations.RemoveField(
            model_name='atonormativ',
            name='data',
        ),
        migrations.RemoveField(
            model_name='atonormativ',
            name='doe_numero',
        ),
        migrations.RemoveField(
            model_name='atonormativ',
            name='usr_cadastro',
        ),
        migrations.AddField(
            model_name='atonormativ',
            name='numero',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='boletimgerado',
            name='status',
            field=models.CharField(choices=[('revisao', 'Revisão'), ('aprovado', 'Aprovado')], default='revisao', max_length=10),
        ),
        migrations.AlterField(
            model_name='atonormativ',
            name='dt_cadastro',
            field=models.DateTimeField(null=True, verbose_name='Data de cadastro'),
        ),
        migrations.AlterField(
            model_name='atonormativ',
            name='publicado',
            field=models.CharField(default='n', max_length=1, null=True, verbose_name='Publicado'),
        ),
    ]
