# Generated by Django 4.1.3 on 2023-08-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_remove_atonormativ_criador_atonormativ_setor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atonormativ',
            name='setor',
        ),
    ]
