# Generated by Django 4.1.3 on 2023-08-16 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_remove_atonormativ_setor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atonormativ',
            name='pendestes_texto',
        ),
    ]
