# Generated by Django 4.1.3 on 2023-08-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_remove_atonormativ_pendestes_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='atonormativ',
            name='criador',
            field=models.CharField(default='user', max_length=45, verbose_name='Criador'),
        ),
        migrations.AddField(
            model_name='atonormativ',
            name='pendestes_texto',
            field=models.TextField(default='Sem pendencias', max_length=1000, null=True, verbose_name='Texto pendentes'),
        ),
    ]
