# Generated by Django 4.1.3 on 2023-08-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_atonormativ_criador_atonormativ_pendestes_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='atonormativ',
            name='setores_uea',
            field=models.PositiveIntegerField(max_length=50, null=True),
        ),
    ]
