# Generated by Django 4.1.3 on 2023-08-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_atonormativ_setores_uea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atonormativ',
            name='setores_uea',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
