# Generated by Django 4.1.3 on 2023-08-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_alter_atonormativ_setores_uea'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletimgerado',
            name='setores_uea',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
