# Generated by Django 4.1.3 on 2023-08-17 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_boletimgerado_setores_uea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletimgerado',
            name='setores_uea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.atonormativ'),
        ),
    ]
