# Generated by Django 4.1.3 on 2023-08-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_alter_boletimgerado_setores_uea'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinantesBoletim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reitor', models.CharField(max_length=100)),
                ('vice_reitor', models.CharField(max_length=100)),
                ('reitor_admin', models.CharField(max_length=100)),
                ('reitor_pes_grad', models.CharField(max_length=100)),
                ('reitor_ens', models.CharField(max_length=100)),
                ('reitor_plan', models.CharField(max_length=100)),
                ('reitor_int', models.CharField(max_length=100)),
                ('reitor_ext', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
