# Generated by Django 4.1.3 on 2023-09-06 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_assinantesboletim'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtoHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_hash', models.CharField(max_length=64, unique=True)),
                ('ato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ato_hashes', to='core.atonormativ')),
            ],
        ),
    ]
