# Generated by Django 4.1.3 on 2023-09-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_atohash_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atohash',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='temp/'),
        ),
    ]
