# Generated by Django 4.1.3 on 2023-09-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_alter_atohash_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atonormativ',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
